// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 17/03/2025 23:49:56
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/denis/Documents/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/denis/Documents/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/denis/Documents/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/denis/Documents/portfolio/plugins/**/*.{js,ts,mjs}","/home/denis/Documents/portfolio/composables/**/*.{js,ts,mjs}","/home/denis/Documents/portfolio/utils/**/*.{js,ts,mjs}","/home/denis/Documents/portfolio/pages/about-me.vue","/home/denis/Documents/portfolio/pages/contact-me.vue","/home/denis/Documents/portfolio/pages/index.vue","/home/denis/Documents/portfolio/pages/projects.vue","/home/denis/Documents/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/denis/Documents/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/denis/Documents/portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;